Feature/recuperation bodacc
KissKissBankBank/bodacc pull request #1
Opened 2018-01-08 11:08 UTC by Mcastres

Recuperation des annonces via Nokogiri et Mechanize

2018-01-09 09:52 UTC, sunny commented on Gemfile
> +git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
On peut mettre un espace entre `{` et `|` ici ?

Comme style de code on essaie d'uniformiser notre style à tous pour suivre les règles de https://github.com/KissKissBankBank/fashion_police

Tu peux aussi t'aider de la gemme `rubocop` et des règles de https://github.com/KissKissBankBank/fashion_police/issues/5 (et même lancer un auto-correct pour la première fois).

2018-01-09 09:54 UTC, Mcastres commented on Gemfile
> +git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
Ok je vais faire ça

2018-01-09 10:48 UTC, sunny requested changes
Premier batch de retours. De manière générale, `rubocop` devrait aider à régler les autres soucis.

2018-01-09 10:48 UTC, sunny commented on Gemfile
> +gem 'pg'
Est-ce qu'on peut mettre un petit commentaire au dessus de chaque gemme pour la décrire ? Au moment de mettre à jour c'est pratique de savoir ce que chaque gemme apporte au projet, surtout quand la liste s'allonge.

Par exemple : 

```rb
# Web scraper.
gem 'mechanize'

# Print color to the console.
gem 'colorize'

# PostgreSQL db.
gem 'pg'
```

2018-01-09 10:48 UTC, sunny commented on README.md
> +Bodacc est un scrapper qui insère toutes les annonces du Bodacc (2008-2018) en base de données [Bodacc](https://echanges.dila.gouv.fr/OPENDATA/BODACC/)
Est-ce que c'est vraiment limité à 2018, ou bien est-ce que c'est plutôt jusque l'année en cours ?

2018-01-09 10:48 UTC, sunny commented on README.md
> +Bodacc est un scrapper qui insère toutes les annonces du Bodacc (2008-2018) en base de données [Bodacc](https://echanges.dila.gouv.fr/OPENDATA/BODACC/)
Est-ce qu'on peut écrire le README en anglais ? On a pris le pli d'écrire tout ce qui est dans nos repos en anglais, que ça soit les README, les commentaires, les commits.

Les issues, PRs et commentaires sur GitHub qu'on se fait entre nous peuvent rester en français. La seule exception est le titre des PRs car au moment de merger on utilise la stratégie "Squash and Merge" qui transforme une PR en un commit.

2018-01-09 10:48 UTC, sunny commented on README.md
> +### Lauch scrapper
`Launch` plutôt.

2018-01-09 10:48 UTC, sunny commented on README.md
> +Bodacc utilise la gem [Nokogiri](https://github.com/sparklemotion/nokogiri) et la gem [Mechanize](https://github.com/sparklemotion/nokogiri) afin de scrapper et télécharger les fichiers. Apres les av
Il faut sans doute ajouter `nokogiri` dans le `Gemfile` du coup.

2018-01-09 10:48 UTC, sunny commented on scraper.rb
> +require 'active_record'
Il faut sans doute l'ajouter dans le Gemfile également aussi ?

2018-01-09 10:48 UTC, sunny commented on scraper.rb
> +)
De ce que je comprends, pour pouvoir lancer ce script il faut préalablement créer une BDD avec ces infos. Peut-être qu'il faut dire dans le README que c'est une étape nécessaire pour lancer ce script ?

2018-01-09 10:48 UTC, sunny commented on scraper.rb
> +[
En Ruby on peut se servir de l'opérateur de "range" pour faire cette liste. 

```rb
years = 2008..2017
```

Ça te fait une liste d'entiers consécutifs. Du coup, plus bas, il faudra faire la vérification avec un entier également et plus un string.

```rb
years.include?('2015'.to_i) # => true
```

2018-01-09 10:48 UTC, sunny commented on scraper.rb
> +# end
Pourquoi as-t-on besoin de cette méthode en commentaire ? Peux-t-on carrément la supprimer ?

2018-01-09 10:48 UTC, sunny commented on scraper.rb
> +      i = i + 1
On peut éviter de gérer cette incrémentation en utilisant `each_with_index` à la place de `each`, ce qui donnera quelque chose d'un peu plus fonctionnel.

2018-01-09 10:48 UTC, sunny commented on scraper.rb
> +    system("rm "+file)
Plutôt que d'utiliser `system`, on préfère utiliser la librairie `FileUtils` qui est plus stable et plus portable.

2018-01-09 10:48 UTC, sunny commented on scraper.rb
> +puts "Bye !"
En anglais on évite de mettre des espaces avant les `!` (contrairement au français !).

2018-01-09 10:48 UTC, sunny commented on scraper.rb
> +    # system('rm tmp/xml/BILAN/* tmp/xml/BILAN/* tmp/xml/BILAN/* tmp/xml/BILAN/*')
Est-ce que cette ligne te sert de temps en temps ? Sinon peut-on retirer carrément le commentaire ?

2018-01-09 10:48 UTC, sunny commented on README.md
> +$> pg_dump bodacc < database_dump
Que contient ce dump ? Est-ce qu'il contient des données ou uniquement des tables vides ?

2018-01-09 10:52 UTC, Mcastres commented on README.md
> +$> pg_dump bodacc < database_dump
Tables vides uniquement

2018-01-10 11:46 UTC, sunny commented on README.md
> +$> pg_dump bodacc < database_dump
👍

2018-01-10 15:44 UTC, Mcastres commented
Il manque quelques erreurs coté Rubocop

2018-01-22 16:20 UTC, sunny requested changes

2018-01-22 16:20 UTC, sunny commented on scraper.rb
> +require 'active_record'
✅

2018-01-22 16:20 UTC, sunny commented on Gemfile
> +# frozen_string_literal: true
On peut se passer de cette ligne, on a désactivé le cop sur l'ensemble des autres fichiers.

2018-01-22 16:20 UTC, sunny commented on Gemfile
> +gem 'nokogiri'
On peut ajouter un petit commentaire pour nokogiri ? `# XML parser` par exemple.

2018-01-22 16:20 UTC, sunny commented on README.md
> +These instructions will get you a copy of the project up and running on your local machine for development and testing purposes. See deployment for notes on how to deploy the project on a live system
On peut retirer "See deployment" vu qu'on a pas de section deployment, non ?

2018-01-22 16:20 UTC, sunny commented on README.md
> +The repository include a dump of the empty database called "database_dump". Create your database with it by running the following command:
Est-ce qu'on peut suffixer ce fichier de `.sql` ? Ça permets de mieux le distinguer dans les éditeurs.

2018-01-22 16:20 UTC, sunny commented on README.md
> +$> bundle install
Je ne sais pas s'il y a une vraie règle mais par convention j'ai plutôt vu juste `$` sur un terminal type bash, et `>` utilisé comme indicateur de démarrage de ligne sur une console Ruby.

2018-01-22 16:20 UTC, sunny commented on README.md
> +```
On peut mettre `sh` ici en Markdown pour GitHub pour qu'il fasse la bonne coloration sur chaque groupe de code.

2018-01-22 16:20 UTC, sunny commented on README.md
> +Bodacc use the [Nokogiri](https://github.com/sparklemotion/nokogiri) gem and the [Mechanize](https://github.com/sparklemotion/nokogiri) gem in order to scrape and download every files. After unzippin
`insert` -> `inserts`

2018-01-22 16:20 UTC, sunny commented on README.md
> +At the end, the script create a 'last_update.txt' file which contain the last time bodacc announcements were inserted into database preventing to download announcements that are already added.
`create` -> `creates`

2018-01-22 16:20 UTC, sunny commented on README.md
> +If you use this scraper for the first time be aware that inserting everything from 2008 to the year before actual will take a lot of time (you'll have time to watch the Star Wars saga with all the bo
Les deux paragraphes précédents méritent un petit `.` à la fin.

2018-01-22 16:20 UTC, sunny commented on README.md
> +At the end, the script create a 'last_update.txt' file which contain the last time bodacc announcements were inserted into database preventing to download announcements that are already added.
Tu peux entour `last_update.txt` de backticks, ça fera une plus jolie coloration en Markdown pour dire que c'est du code.

```
`last_update.txt`
```

2018-01-22 16:20 UTC, sunny commented on README.md
> +* [Ruby](https://www.ruby-lang.org/fr/) - The programming language used
Je pense qu'on peut retirer toute cette partie, c'est assez redondant tu crois pas ?

2018-01-22 16:20 UTC, sunny commented on modules/bilan.rb
> +      Bilan.create( \
On peut se passer du `\` ici, il me semble. (Idem pour les autres `( \`.)

2018-01-22 16:20 UTC, sunny commented on modules/bilan.rb
> +      puts 'Announcement ' + numero_annonce_ap + ' has been deleted'
En Ruby on préfère souvent utiliser de l'interpolation plutôt que de la concaténation. Ici ça donnerait `"Announcement #{numero_annonce_ap} has been deleted"`. (Idem pour les autres utilisation de `+`.)

2018-01-22 16:20 UTC, sunny commented on modules/immatriculation.rb
> +                  elsif !annonce.search('categorieCreation').blank?
Plutôt que `!foo.blank?` on peut utiliser la méthode inverse `foo.present?` qui évite la double négation. C'est un poil plus facile à lire, je trouve.

2018-01-22 16:20 UTC, sunny commented on modules/immatriculation.rb
> +                                        type_annonce: 'annonce', siren: siren)
On peut mettre `siren` à la ligne comme les autres args ?

2018-01-22 16:20 UTC, sunny commented on modules/immatriculation.rb
> +      return if to_delete.nil?
Attention, un `where`, même s'il ne trouve aucun résultat, n'est jamais `nil?`. Ici c'est plutôt `empty?` que tu veux, je pense.

2018-01-22 16:20 UTC, sunny commented on modules/modification.rb
> +          annonce.search('modificationsGenerales/precedentExploitantPM/numeroImmatriculation/numeroIdentification').text,
Est-ce qu'on peut réussir à avoir des lignes qui tiennent sous 80 chars ? (Idem pour les autres lignes.)

2018-01-22 16:20 UTC, sunny commented on modules/bilan.rb
> +      t = avis.search('typeAnnonce').children.to_s.gsub!(/[^0-9A-Za-z]/, '')
Est-ce qu'on peut éviter d'avoir des noms de variables aussi courts ? Tout est plus facile à lire si on utilise quelque chose de plus long mais plus explicite, par exemple ici `type_annonce`. (Idem pour les autres `t =`.)

2018-01-22 16:20 UTC, sunny commented on scraper.rb
> +                11.years.ago
C'est pas plutôt `years.first` ici ? (Ça peut éviter l'année prochaine de mettre 12.)

2018-01-22 16:20 UTC, sunny commented on scraper.rb
> +  system('tar -xf ' + path + ' -C ' + path.gsub(file, '') + '; rm ' + path)
On peut utiliser `FileUtils` pour supprimer le path ? Ça simplifiera un poil cette ligne.

2018-01-22 16:20 UTC, sunny commented on scraper.rb
> +# Download every new files
`files` -> `file`

2018-01-23 08:59 UTC, Mcastres commented on modules/modification.rb
> +          annonce.search('modificationsGenerales/precedentExploitantPM/numeroImmatriculation/numeroIdentification').text,
Pour celles dans ce fichier c'est plutôt compliqué vue que je dois absolument avoir la string `modificationsGenerales/precedentExploitantPP/numeroImmatriculation/numeroIdentification` et je ne vois pas comment la racourcir

2018-01-23 09:07 UTC, Mcastres commented on scraper.rb
> +                11.years.ago
Bien vu !

2018-01-25 11:17 UTC, sunny commented on modules/modification.rb
> +          annonce.search('modificationsGenerales/precedentExploitantPM/numeroImmatriculation/numeroIdentification').text,
Ah ouais, c'est pas très pratique du coup. Tu peux peut-être te servir du `\`.

Par exemple :

```rb
module Scrapper
  class ModificationAction
    def self.create(annonce, file, date)
      # …
      Modification.create(
        # …
        denomination_pepm:
          annonce.search(
            'modificationsGenerales/precedentExploitantPM/denomination'
          ).text,
        siren_pepm:
          annonce.search(
            'modificationsGenerales/precedentExploitantPM/' \
            'numeroImmatriculation/numeroIdentification'
          ).text,
        # …
      )
    end
  end
end
```

2018-01-26 10:51 UTC, Mcastres commented on modules/modification.rb
> +          annonce.search('modificationsGenerales/precedentExploitantPM/numeroImmatriculation/numeroIdentification').text,
Nickel merci

2018-02-11 13:30 UTC, sunny requested changes

2018-02-11 13:30 UTC, sunny commented on modules/bilan.rb
> +                        typeAnnonce').children.to_s.gsub!(/[^0-9A-Za-z]/, '')
Ce retour à la ligne me paraît étrange ici, c'est voulu d'avoir un string sur deux lignes ? Pour mieux indenter, on ferait plutôt :

```rb
type_annonce =
  avis.search(…)
```

2018-02-11 13:30 UTC, sunny commented on modules/immatriculation.rb
> +                        typeAnnonce').children.to_s.gsub!(/[^0-9A-Za-z]/, '')
(Même remarque).

2018-02-11 13:30 UTC, sunny commented on modules/immatriculation.rb
> +      categorie
Nul besoin d'en faire une variable, ici. On peut juste profiter du fait que Ruby retourne la dernière chose évaluée.

```rb
def self.categorie(annonce)
  if …
    'Vente'
  elsif …
    'Creation'
  else
    'Immatriculation'
  end
end
```

2018-02-11 13:30 UTC, sunny commented on modules/immatriculation.rb
> +    end
Est-ce que cette méthode n'est pas strictement identique à `categorie` ?

2018-02-11 13:30 UTC, sunny commented on modules/modification.rb
> +                      typeAnnonce').children.to_s.gsub!(/[^0-9A-Za-z]/, '')
Ici aussi le string sur deux lignes me paraît étrange.

2018-02-11 13:30 UTC, sunny commented on modules/pcl.rb
> +                      typeAnnonce').children.to_s.gsub!(/[^0-9A-Za-z]/, '')
Pareil pour le string ici.

2018-02-11 13:30 UTC, sunny commented on modules/radiation.rb
> +                  typeAnnonce').children.to_s.gsub!(/[^0-9A-Za-z]/, '')
Pareil pour ce string multiligne.

2018-02-11 13:30 UTC, sunny commented on scraper.rb
> +require 'pg' # or 'mysql2' or 'sqlite3'
Pour toutes les gemmes qui sont déjà listées dans ton `Gemfile`, tu peux remplacer tous leurs `require` par :

```rb
require 'bundler/setup'
Bundler.require(:default)
```

Ça va les require ici.

2018-02-11 13:30 UTC, sunny commented on scraper.rb
> +puts 'Bye!'
Est-ce que tu peux déplacer tout ce qui se trouve dans ce script dans un module à part ?

Idéalement ici je ne verrais que les require, la configuration à la BDD et l'appel aux modules.

2018-02-26 17:33 UTC, williampollet commented on modules/archives.rb
> +        # Gonna catch them all !
^^

2018-02-27 11:29 UTC, cyrill62 requested changes
Du coup ce serait intéressant (surtout pour la partie hébergement), de : 

1. Utiliser des variables d'environnement pour tout ce qui est config (BDD, clés d'API)
2. Utiliser AWS S3 pour stocker les fichiers téléchargés depuis le service, pour ne pas à avoir à les retélécharger depuis le service à chaque lancement ou si on les perds sur le disque local.

2018-02-27 13:19 UTC, williampollet commented on README.md
> +### Structure
Pas forcément nécessaire (surtout que ca sera obsolète quand tu changeras la structure)

2018-02-27 13:19 UTC, williampollet commented on main.rb
> +
#require services

2018-02-27 13:19 UTC, williampollet commented on modules/actual.rb
> +  class Scrape
Est ce que ca ne serait pas un service? (le `scrapper`)

2018-02-27 13:19 UTC, williampollet commented on modules/archives.rb
> +  class Scrape
comment ca se fait que ici dans le modules archives la classe et le module on le même nom que `scrapper`?

2018-02-27 13:19 UTC, williampollet commented on modules/actual.rb
> +  class Scrape
pourquoi le nom du fichier est `actual`?

2018-02-27 13:35 UTC, Mcastres commented on modules/actual.rb
> +  class Scrape
Il y a archives.rb qui télécharge les archives et actual.rb qui lui s'occupe des annonces de cette année

2018-02-28 08:49 UTC, williampollet commented on modules/scraper.rb
> +  class Core
pourquoi est ce que tu as à la fois un module et une classe ? Que penses tu de faire juste une classe `Scraper` ou un module `Scraper` ? Je trouve que ca serait plus simple. (après je manque peut être quelque chose)

2018-02-28 08:51 UTC, williampollet commented on services/archives.rb
> +  class ScrapeArchives
Idem ici, tu pourrais, soit faire une classe `archives`, ou alors mettre ses méthodes en commun avec la classe `scrapper` (qui aurait une méthode `scrape_archives`, et une autre `scrape`)

2018-02-28 10:20 UTC, sunny commented on README.md
> +The repository include a dump of the empty database called "database_dump". Create your database with it by running the following command:
✅

2018-02-28 10:21 UTC, sunny commented on main.rb
> +
✅

2018-03-01 14:41 UTC, williampollet approved these changes

2018-03-01 16:32 UTC, sunny approved these changes

2018-03-01 16:50 UTC, Mcastres commented
Concernant ta review Cyril, l'utilisation d'une variable d'environnement pour la config DB est faite. Ensuite pas besoin de S3, j'ai fais en sorte que le script n'ai plus besoin du fichier `last_update`, donc plus besoin de le stocker.

2018-03-21 16:58 UTC, cyrill62 requested changes

2018-03-21 16:58 UTC, cyrill62 commented on docker-entrypoint.sh
> +    DATABASE_URL=postgres://localhost:5432/bodacc ruby main.rb
Du coup le `DATABASE_URL` est passé par `docker` ou `docker-compose` ou `ecs-cli`

Il viens de l'extérieur, ce qui est mieux pour lancer ton application avec différentes configurations

2018-03-21 16:58 UTC, cyrill62 commented on docker-entrypoint.sh
> +    pg_dump bodacc < structure.sql
Ici ce serait plutôt `pg_restore` ou `psql`

2018-03-21 16:58 UTC, cyrill62 commented on Dockerfile
> +
Il va te manque les utilitaires de `postgres`, qui sont très dépendants de la du serveur que tu souhaites utiliser.

Tu peux t'inspirer de : https://github.com/KissKissBankBank/gringotts/blob/master/Dockerfile#L7

2018-03-23 14:14 UTC, cyrill62 commented on Dockerfile
> +
:white_check_mark:

2018-03-29 16:47 UTC, williampollet commented on docker-compose.yml
>        DATABASE_URL: postgres://root:123456@db:5432/bodacc
Ici c'est des variables de prod / dev / staging? Est ce qu'on pourrait les mettre dans une variable d'environnement?

2018-05-25 10:45 UTC, merged